#!/bin/bash
# -----------------------------------------------------------------------------
# File:        refresh-version.sh
# Path:        scripts/refresh-version.sh
#
# Project:     Hazard3-Doom
# Purpose:     Refresh generated version files from root /VERSION
#
# Copyright (c) 2026 gojimmypi
#
# Licensed under the Apache License, Version 2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# This software is provided under the terms of the applicable license.
# See LICENSES/Apache-2.0.txt for the complete license terms.
# See LICENSING.md for project licensing policy and scope.
# -----------------------------------------------------------------------------

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/.." && pwd)"
version_file="${repo_root}/VERSION"
c_output="${repo_root}/src/generated/version.h"
web_output="${repo_root}/web/generated/version.js"
mode="update"

usage()
{
    cat <<EOF_USAGE
Usage: ${0##*/} [--check]

Generate the Hazard3-Doom C and web version files from the root VERSION file.

  --check     Verify the generated files are current without changing them.
  -h, --help  Show this help text.
EOF_USAGE
}

while (( $# > 0 )); do
    case "$1" in
    --check)
        mode="check"
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        printf 'ERROR: Unknown option: %s\n\n' "$1" >&2
        usage >&2
        exit 2
        ;;
    esac
    shift
done

if [[ ! -f "${version_file}" ]]; then
    printf 'ERROR: VERSION file not found: %s\n' "${version_file}" >&2
    exit 1
fi

version="$(tr -d '\r\n' < "${version_file}")"
if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
    printf 'ERROR: Invalid VERSION value: %s\n' "${version}" >&2
    printf 'Expected a semantic version such as 0.2.0 or 0.2.0-rc.1.\n' >&2
    exit 1
fi

numeric_version="${version%%[-+]*}"
IFS='.' read -r version_major version_minor version_patch <<< "${numeric_version}"

c_tmp="$(mktemp)"
web_tmp="$(mktemp)"
trap 'rm -f "${c_tmp}" "${web_tmp}"' EXIT

cat > "${c_tmp}" <<EOF_C
/* Generated by scripts/refresh-version.sh from VERSION. Do not edit. */
#ifndef HAZARD3_DOOM_GENERATED_VERSION_H
#define HAZARD3_DOOM_GENERATED_VERSION_H

#define HAZARD3_DOOM_VERSION "${version}"
#define HAZARD3_DOOM_VERSION_DISPLAY "v${version}"
#define HAZARD3_DOOM_VERSION_MAJOR ${version_major}
#define HAZARD3_DOOM_VERSION_MINOR ${version_minor}
#define HAZARD3_DOOM_VERSION_PATCH ${version_patch}

#endif
EOF_C

cat > "${web_tmp}" <<EOF_WEB
"use strict";

// Generated by scripts/refresh-version.sh from VERSION. Do not edit.
window.HAZARD3_DOOM_VERSION = Object.freeze({
    version: "${version}",
    display: "v${version}",
});
EOF_WEB

update_file()
{
    local source_file="$1"
    local destination_file="$2"

    if [[ -f "${destination_file}" ]] && cmp -s "${source_file}" "${destination_file}"; then
        printf 'Unchanged: %s\n' "${destination_file#"${repo_root}/"}"
        return
    fi

    cp "${source_file}" "${destination_file}"
    chmod 0644 "${destination_file}"
    printf 'Updated:   %s\n' "${destination_file#"${repo_root}/"}"
}

check_file()
{
    local expected_file="$1"
    local generated_file="$2"

    if [[ ! -f "${generated_file}" ]]; then
        printf 'ERROR: Missing generated version file: %s\n' \
            "${generated_file#"${repo_root}/"}" >&2
        return 1
    fi

    if ! cmp -s "${expected_file}" "${generated_file}"; then
        printf 'ERROR: Generated version file is stale: %s\n' \
            "${generated_file#"${repo_root}/"}" >&2
        return 1
    fi

    printf 'Current:   %s\n' "${generated_file#"${repo_root}/"}"
}

if [[ "${mode}" == "check" ]]; then
    status=0
    check_file "${c_tmp}" "${c_output}" || status=1
    check_file "${web_tmp}" "${web_output}" || status=1
    printf 'Version:   v%s\n' "${version}"
    if (( status != 0 )); then
        printf 'Run ./scripts/refresh-version.sh to refresh generated version files.\n' >&2
        exit "${status}"
    fi
    exit 0
fi

mkdir -p "$(dirname -- "${c_output}")" "$(dirname -- "${web_output}")"
update_file "${c_tmp}" "${c_output}"
update_file "${web_tmp}" "${web_output}"
printf 'Version:   v%s\n' "${version}"
